-- AlterTable
ALTER TABLE "Booking" ALTER COLUMN "attendees" DROP DEFAULT,
ALTER COLUMN "bookedBy" DROP DEFAULT,
ALTER COLUMN "location" DROP DEFAULT,
ALTER COLUMN "meetingTitle" DROP DEFAULT,
ALTER COLUMN "status" DROP DEFAULT;
